# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from itertools import starmap
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
#from _future_ import print_function
import xlrd
import matplotlib.pyplot as plt;
import numpy as np
import matplotlib.pyplot as plt
import statistics
from zope.interface.interfaces import ObjectEvent
plt.rcdefaults()
def iqr_fun(l, n,self,mad):
    l.sort()
    if len(l) % 2 != 0:
        q2 = l[(len(l) - 1) // 2]
        if (((len(l) - 1) // 2) % 2 != 0):
            q1 = l[(((len(l) - 1) // 2) - 1) // 2];
            q3 = l[(len(l) - 1) - ((((len(l) - 1) // 2) - 1) // 2)]
        else:
            q1 = (l[((len(l) - 1) // 2) // 2] + l[(((len(l) - 1) // 2) // 2) - 1]) / 2
            q3 = (l[len(l) - (((len(l) - 1) // 2) // 2)] + l[(len(l) - (((len(l) - 1) // 2) // 2)) - 1]) / 2
    elif len(l) % 2 == 0:
        q2 = (l[len(l) // 2] + l[len(l) // 2 - 1]) / 2
        if ((len(l) // 2) % 2 != 0):
            q1 = l[((len(l) // 2) - 1) // 2];
            q3 = l[len(l) - 1 - (((len(l) // 2) - 1) // 2)]
        else:
            q1 = (l[len(l) // 4] + l[(len(l) // 4) - 1]) / 2
            q3 = (l[len(l) - (len(l) // 4)] + l[(len(l) - (len(l) // 4)) - 1]) / 2
    iqr=q3-q1
    self.lbl_q1.setText(str(q1))
    self.lbl_q2.setText(str(q2))
    self.lbl_q3.setText(str(q3))
    if (q2-q1)>(q3-q2):
        self.lbl_kindofiqr.setText("Left Skew")
    if (q2-q1)<(q3-q2):
        self.lbl_kindofiqr.setText("Right Skew")
    if (q2-q1)==(q3-q2):
        self.lbl_kindofiqr.setText("Normal")
    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)
    lisuper = []
    lislower = []
    extremevalueuper = []
    extremevaluelowe = []
    for i in range(0, len(l)):
        if (l[i] > float(upper_bound)):
            lisuper.append(str(l[i]))
        if (l[i] < float(lower_bound)):
            lislower.append(str(l[i]))
        if (l[i] > float(q3 + 3 * iqr)):
            extremevalueuper.append(str(l[i]))
        if (l[i] < float(q1 - 3 * iqr)):
            extremevaluelowe.append(str(l[i]))
    Outliers=""
    extreamvale=""
    print(len(lisuper))
    for i in range (0,len(lisuper)):
        Outliers=Outliers+lisuper[i]
    for i in range (0,len(lislower)):
        Outliers=Outliers+lislower[i]
    if(len(Outliers)==0):
        self.lbl_outliers.setText("Not Found")
    if(len(Outliers)!=0):
        self.lbl_outliers.setText(str(Outliers))
    for i in range (0,len(extremevalueuper)):
        extreamvale=extreamvale+extremevalueuper[i]
    for i in range (0,len(extremevaluelowe)):
        extreamvale=extreamvale+extremevaluelowe[i]
    if (len(extreamvale) == 0):
        self.lbl_outliers.setText("Not Found")
    if (len(extreamvale) != 0):
        self.lbl_extreme.setText(extreamvale)
    return (q3 - q1)

def getx(elementLi=[], mean=0.0):
    subLi = []
    sum=0;
    for element in elementLi:
        y=math.pow((element-mean),2)
        sum=sum+y
    #sum=math.fsum(subLi)
    return sum

def getVar(elementLi=[], mean=0.0):
    sum = getx(elementLi, mean)
    #sqr = math.sqrt(sum)
    #print(len(elementLi))
    s = sum / (len(elementLi) - 1)
    #print(s)
    return s

def getZ_Score(elementLi=[]):
    mean = statistics.mean(elementLi)
    var = getVar(elementLi, mean)
    zLi = []
    for element in elementLi:
        x=element - mean
        y=math.sqrt(var)
        zLi.append(x / y)
    return zLi
z_values = {}
def init():
    z_table = xlrd.open_workbook('ZScores&NormalDistribution.xls')
    sheet = z_table.sheet_by_index(0)
    for i in range(0, 717):
        s1 = ''
        s1 = str(sheet.cell(i, 0))
        s1 = s1.replace('number:', '')
        s2 = ''
        s2 = str(sheet.cell(i, 1))
        s2 = s2.replace('number:', '')
        z_values[s1] = round(float(s2),4)

def get_z(x):
    x1 = x2 = 0.0
    flag = False
    c = c1 = c2 = ''
    for i, j in z_values.items():
        if j < x:
            x1 = j
            c1 = i
        elif j == x:
            c = i
            flag = True
            break
        elif j > x:
            x2 = j
            c2 = i
            break
    if flag == False:
        if x - x1 > x2 - x:
            c = c2
        elif x - x1 < x2 - x:
            c = c1
    if c.find('-') != -1:
        c = c.replace('-', '')
    d=float(c)
    return d


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        init()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 1315)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(24)
        font.setItalic(True)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setLineWidth(18)
        self.label.setObjectName("label")
        self.combo_selectProblem = QtWidgets.QComboBox(self.centralwidget)
        self.combo_selectProblem.setGeometry(QtCore.QRect(400, 70, 111, 22))
        self.combo_selectProblem.setEditable(False)
        self.combo_selectProblem.setCurrentText("")
        self.combo_selectProblem.setObjectName("combo_selectProblem")
        self.combo_selectProblem.addItem("")
        self.combo_selectProblem.setItemText(0, "")
        self.combo_selectProblem.addItem("")
        self.combo_selectProblem.addItem("")
        self.combo_selectProblem.addItem("")
        self.combo_selectProblem.addItem("")
        self.combo_selectProblem.addItem("")
        self.combo_selectProblem.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.widget_pie_par = QtWidgets.QWidget(self.centralwidget)
        self.widget_pie_par.setGeometry(QtCore.QRect(0, 170, 821, 111))
        self.widget_pie_par.setObjectName("widget_pie_par")
        self.widget_pie_par.hide()
        self.txt_nameofdata = QtWidgets.QLineEdit(self.widget_pie_par)
        self.txt_nameofdata.setGeometry(QtCore.QRect(180, 20, 301, 20))
        self.txt_nameofdata.setObjectName("txt_nameofdata")
        self.btn_okpiepar = QtWidgets.QPushButton(self.widget_pie_par)
        self.btn_okpiepar.setGeometry(QtCore.QRect(610, 60, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_okpiepar.setFont(font)
        self.btn_okpiepar.setObjectName("btn_okpiepar")
        self.label_4 = QtWidgets.QLabel(self.widget_pie_par)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comb_pie_par = QtWidgets.QComboBox(self.widget_pie_par)
        self.comb_pie_par.setGeometry(QtCore.QRect(680, 30, 131, 22))
        self.comb_pie_par.setObjectName("comb_pie_par")
        self.comb_pie_par.addItem("")
        self.comb_pie_par.setItemText(0, "")
        self.comb_pie_par.addItem("")
        self.comb_pie_par.addItem("")
        self.txt_amountofdatapie = QtWidgets.QLineEdit(self.widget_pie_par)
        self.txt_amountofdatapie.setGeometry(QtCore.QRect(180, 70, 301, 20))
        self.txt_amountofdatapie.setObjectName("txt_amountofdatapie")
        self.label_5 = QtWidgets.QLabel(self.widget_pie_par)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_pie_par)
        self.label_6.setGeometry(QtCore.QRect(500, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.widget_iqr = QtWidgets.QWidget(self.centralwidget)
        self.widget_iqr.setGeometry(QtCore.QRect(0, 170, 821, 301))
        self.widget_iqr.setObjectName("widget_iqr")
        self.widget_iqr.hide()
        self.label_16 = QtWidgets.QLabel(self.widget_iqr)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.txt_nameofdataiqr = QtWidgets.QLineEdit(self.widget_iqr)
        self.txt_nameofdataiqr.setGeometry(QtCore.QRect(180, 20, 371, 20))
        self.txt_nameofdataiqr.setObjectName("txt_nameofdataiqr")
        self.btn_okiqr = QtWidgets.QPushButton(self.widget_iqr)
        self.btn_okiqr.setGeometry(QtCore.QRect(610, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_okiqr.setFont(font)
        self.btn_okiqr.setObjectName("btn_okiqr")
        self.label_17 = QtWidgets.QLabel(self.widget_iqr)
        self.label_17.setGeometry(QtCore.QRect(40, 70, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lbl_mode_2 = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_mode_2.setGeometry(QtCore.QRect(160, 90, 47, 13))
        self.lbl_mode_2.setText("")
        self.lbl_mode_2.setObjectName("lbl_mode_2")
        self.lbl_midean_2 = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_midean_2.setGeometry(QtCore.QRect(160, 140, 47, 13))
        self.lbl_midean_2.setText("")
        self.lbl_midean_2.setObjectName("lbl_midean_2")
        self.lbl_mean_2 = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_mean_2.setGeometry(QtCore.QRect(160, 190, 47, 13))
        self.lbl_mean_2.setText("")
        self.lbl_mean_2.setObjectName("lbl_mean_2")
        self.label_22 = QtWidgets.QLabel(self.widget_iqr)
        self.label_22.setGeometry(QtCore.QRect(40, 170, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_iqr)
        self.label_23.setGeometry(QtCore.QRect(40, 120, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_iqr)
        self.label_24.setGeometry(QtCore.QRect(40, 220, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.lbl_iqr = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_iqr.setGeometry(QtCore.QRect(100, 240, 47, 13))
        self.lbl_iqr.setText("")
        self.lbl_iqr.setObjectName("lbl_iqr")
        self.label_26 = QtWidgets.QLabel(self.widget_iqr)
        self.label_26.setGeometry(QtCore.QRect(30, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lbl_kindofiqr = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_kindofiqr.setGeometry(QtCore.QRect(170, 280, 47, 13))
        self.lbl_kindofiqr.setText("")
        self.lbl_kindofiqr.setObjectName("lbl_kindofiqr")
        self.label_32 = QtWidgets.QLabel(self.widget_iqr)
        self.label_32.setGeometry(QtCore.QRect(260, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.widget_iqr)
        self.label_33.setGeometry(QtCore.QRect(260, 70, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.widget_iqr)
        self.label_34.setGeometry(QtCore.QRect(260, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lbl_q1 = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_q1.setGeometry(QtCore.QRect(310, 90, 47, 13))
        self.lbl_q1.setText("")
        self.lbl_q1.setObjectName("lbl_q1")
        self.lbl_q2 = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_q2.setGeometry(QtCore.QRect(310, 140, 47, 13))
        self.lbl_q2.setText("")
        self.lbl_q2.setObjectName("lbl_q2")
        self.lbl_q3 = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_q3.setGeometry(QtCore.QRect(320, 190, 47, 13))
        self.lbl_q3.setText("")
        self.lbl_q3.setObjectName("lbl_q3")
        self.label_38 = QtWidgets.QLabel(self.widget_iqr)
        self.label_38.setGeometry(QtCore.QRect(440, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.widget_iqr)
        self.label_39.setGeometry(QtCore.QRect(440, 160, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.lbl_outliers = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_outliers.setGeometry(QtCore.QRect(560, 110, 61, 16))
        self.lbl_outliers.setText("")
        self.lbl_outliers.setObjectName("lbl_outliers")
        self.lbl_extreme = QtWidgets.QLabel(self.widget_iqr)
        self.lbl_extreme.setGeometry(QtCore.QRect(610, 180, 71, 16))
        self.lbl_extreme.setText("")
        self.lbl_extreme.setObjectName("lbl_extreme")

        self.widget_mode = QtWidgets.QWidget(self.centralwidget)
        self.widget_mode.setGeometry(QtCore.QRect(0, 170, 821, 211))
        self.widget_mode.setObjectName("widget_mode")
        self.widget_mode.hide()
        self.label_14 = QtWidgets.QLabel(self.widget_mode)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.txt_nameofdatamode = QtWidgets.QLineEdit(self.widget_mode)
        self.txt_nameofdatamode.setGeometry(QtCore.QRect(180, 20, 371, 20))
        self.txt_nameofdatamode.setObjectName("txt_nameofdatamode")
        self.btn_okmode = QtWidgets.QPushButton(self.widget_mode)
        self.btn_okmode.setGeometry(QtCore.QRect(610, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_okmode.setFont(font)
        self.btn_okmode.setObjectName("btn_okmode")
        self.label_13 = QtWidgets.QLabel(self.widget_mode)
        self.label_13.setGeometry(QtCore.QRect(40, 70, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lbl_mode = QtWidgets.QLabel(self.widget_mode)
        self.lbl_mode.setGeometry(QtCore.QRect(160, 90, 47, 13))
        self.lbl_mode.setText("")
        self.lbl_mode.setObjectName("lbl_mode")
        self.lbl_midean = QtWidgets.QLabel(self.widget_mode)
        self.lbl_midean.setGeometry(QtCore.QRect(160, 140, 47, 13))
        self.lbl_midean.setText("")
        self.lbl_midean.setObjectName("lbl_midean")
        self.lbl_mean = QtWidgets.QLabel(self.widget_mode)
        self.lbl_mean.setGeometry(QtCore.QRect(160, 190, 47, 13))
        self.lbl_mean.setText("")
        self.lbl_mean.setObjectName("lbl_mean")
        self.label_20 = QtWidgets.QLabel(self.widget_mode)
        self.label_20.setGeometry(QtCore.QRect(40, 170, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_mode)
        self.label_21.setGeometry(QtCore.QRect(40, 120, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")

        self.widget_R = QtWidgets.QWidget(self.centralwidget)
        self.widget_R.setGeometry(QtCore.QRect(0, 170, 811, 561))
        self.widget_R.setObjectName("widget_R")
        self.widget_R.hide()
        self.tableWidget_r = QtWidgets.QTableWidget(self.widget_R)
        self.tableWidget_r.setGeometry(QtCore.QRect(300, 130, 501, 301))
        self.tableWidget_r.setObjectName("tableWidget_r")
        self.tableWidget_r.setColumnCount(5)
        self.tableWidget_r.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_r.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_r.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_r.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_r.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_r.setHorizontalHeaderItem(4, item)
        self.label_25 = QtWidgets.QLabel(self.widget_R)
        self.label_25.setGeometry(QtCore.QRect(20, 320, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_18 = QtWidgets.QLabel(self.widget_R)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.txt_nameofdatax = QtWidgets.QLineEdit(self.widget_R)
        self.txt_nameofdatax.setGeometry(QtCore.QRect(210, 20, 371, 20))
        self.txt_nameofdatax.setObjectName("txt_nameofdatax")
        self.btn_okr = QtWidgets.QPushButton(self.widget_R)
        self.btn_okr.setGeometry(QtCore.QRect(650, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_okr.setFont(font)
        self.btn_okr.setObjectName("btn_okr")
        self.txt_nameofdatay = QtWidgets.QLineEdit(self.widget_R)
        self.txt_nameofdatay.setGeometry(QtCore.QRect(210, 70, 371, 20))
        self.txt_nameofdatay.setObjectName("txt_nameofdatay")
        self.label_19 = QtWidgets.QLabel(self.widget_R)
        self.label_19.setGeometry(QtCore.QRect(20, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lb_r = QtWidgets.QLabel(self.widget_R)
        self.lb_r.setGeometry(QtCore.QRect(60, 340, 47, 13))
        self.lb_r.setText("")
        self.lb_r.setObjectName("lb_r")
        self.lb_kindofr = QtWidgets.QLabel(self.widget_R)
        self.lb_kindofr.setGeometry(QtCore.QRect(150, 400, 91, 20))
        self.lb_kindofr.setText("")
        self.lb_kindofr.setObjectName("lb_kindofr")
        self.label_27 = QtWidgets.QLabel(self.widget_R)
        self.label_27.setGeometry(QtCore.QRect(20, 380, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.widget_R)
        self.label_28.setGeometry(QtCore.QRect(10, 110, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.widget_R)
        self.label_29.setGeometry(QtCore.QRect(10, 210, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.widget_R)
        self.label_30.setGeometry(QtCore.QRect(10, 160, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.widget_R)
        self.label_31.setGeometry(QtCore.QRect(10, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lb_xbar = QtWidgets.QLabel(self.widget_R)
        self.lb_xbar.setGeometry(QtCore.QRect(60, 130, 47, 13))
        self.lb_xbar.setText("")
        self.lb_xbar.setObjectName("lb_xbar")
        self.lb_ybar = QtWidgets.QLabel(self.widget_R)
        self.lb_ybar.setGeometry(QtCore.QRect(80, 180, 47, 13))
        self.lb_ybar.setText("")
        self.lb_ybar.setObjectName("lb_ybar")
        self.lb_sx = QtWidgets.QLabel(self.widget_R)
        self.lb_sx.setGeometry(QtCore.QRect(70, 230, 47, 13))
        self.lb_sx.setText("")
        self.lb_sx.setObjectName("lb_sx")
        self.lb_sy = QtWidgets.QLabel(self.widget_R)
        self.lb_sy.setGeometry(QtCore.QRect(70, 280, 47, 13))
        self.lb_sy.setText("")
        self.lb_sy.setObjectName("lb_sy")
        self.label_35 = QtWidgets.QLabel(self.widget_R)
        self.label_35.setGeometry(QtCore.QRect(20, 420, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.lb_b1 = QtWidgets.QLabel(self.widget_R)
        self.lb_b1.setGeometry(QtCore.QRect(80, 440, 47, 13))
        self.lb_b1.setText("")
        self.lb_b1.setObjectName("lb_b1")
        self.lb_b0 = QtWidgets.QLabel(self.widget_R)
        self.lb_b0.setGeometry(QtCore.QRect(80, 490, 47, 13))
        self.lb_b0.setText("")
        self.lb_b0.setObjectName("lb_b0")
        self.label_36 = QtWidgets.QLabel(self.widget_R)
        self.label_36.setGeometry(QtCore.QRect(20, 470, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.widget_R)
        self.label_37.setGeometry(QtCore.QRect(150, 470, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.txt_e = QtWidgets.QLineEdit(self.widget_R)
        self.txt_e.setGeometry(QtCore.QRect(450, 490, 113, 20))
        self.txt_e.setObjectName("txt_e")
        self.btn_oke = QtWidgets.QPushButton(self.widget_R)
        self.btn_oke.setGeometry(QtCore.QRect(600, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_oke.setFont(font)
        self.btn_oke.setObjectName("btn_oke")
        self.lb_e = QtWidgets.QLabel(self.widget_R)
        self.lb_e.setGeometry(QtCore.QRect(210, 490, 47, 13))
        self.lb_e.setText("")
        self.lb_e.setObjectName("lb_e")
        self.label_40 = QtWidgets.QLabel(self.widget_R)
        self.label_40.setGeometry(QtCore.QRect(340, 480, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")

        self.widget_hiostgram = QtWidgets.QWidget(self.centralwidget)
        self.widget_hiostgram.setGeometry(QtCore.QRect(0, 170, 831, 151))
        self.widget_hiostgram.setObjectName("widget_hiostgram")
        self.widget_hiostgram.hide()
        self.txt_nameofdatahistogram = QtWidgets.QLineEdit(self.widget_hiostgram)
        self.txt_nameofdatahistogram.setGeometry(QtCore.QRect(220, 20, 371, 20))
        self.txt_nameofdatahistogram.setObjectName("txt_nameofdatahistogram")
        self.label_15 = QtWidgets.QLabel(self.widget_hiostgram)
        self.label_15.setGeometry(QtCore.QRect(30, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.btn_okhistogram = QtWidgets.QPushButton(self.widget_hiostgram)
        self.btn_okhistogram.setGeometry(QtCore.QRect(640, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_okhistogram.setFont(font)
        self.btn_okhistogram.setObjectName("btn_okhistogram")
        self.label_41 = QtWidgets.QLabel(self.widget_hiostgram)
        self.label_41.setGeometry(QtCore.QRect(260, 80, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.widget_hiostgram)
        self.label_42.setGeometry(QtCore.QRect(30, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.widget_hiostgram)
        self.label_43.setGeometry(QtCore.QRect(490, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.widget_hiostgram)
        self.label_44.setGeometry(QtCore.QRect(490, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.widget_hiostgram)
        self.label_45.setGeometry(QtCore.QRect(30, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.lbl_maxvalue = QtWidgets.QLabel(self.widget_hiostgram)
        self.lbl_maxvalue.setGeometry(QtCore.QRect(160, 70, 61, 16))
        self.lbl_maxvalue.setText("")
        self.lbl_maxvalue.setObjectName("lbl_maxvalue")
        self.lbl_mode_3 = QtWidgets.QLabel(self.widget_hiostgram)
        self.lbl_mode_3.setGeometry(QtCore.QRect(210, 110, 47, 13))
        self.lbl_mode_3.setText("")
        self.lbl_mode_3.setObjectName("lbl_mode_3")
        self.lbl_minvalue = QtWidgets.QLabel(self.widget_hiostgram)
        self.lbl_minvalue.setGeometry(QtCore.QRect(160, 110, 61, 16))
        self.lbl_minvalue.setText("")
        self.lbl_minvalue.setObjectName("lbl_minvalue")
        self.lbl_range = QtWidgets.QLabel(self.widget_hiostgram)
        self.lbl_range.setGeometry(QtCore.QRect(360, 90, 61, 16))
        self.lbl_range.setText("")
        self.lbl_range.setObjectName("lbl_range")
        self.lbl_nclasses = QtWidgets.QLabel(self.widget_hiostgram)
        self.lbl_nclasses.setGeometry(QtCore.QRect(630, 70, 61, 16))
        self.lbl_nclasses.setText("")
        self.lbl_nclasses.setObjectName("lbl_nclasses")
        self.lbl_classwidth = QtWidgets.QLabel(self.widget_hiostgram)
        self.lbl_classwidth.setGeometry(QtCore.QRect(630, 110, 61, 16))
        self.lbl_classwidth.setText("")
        self.lbl_classwidth.setObjectName("lbl_classwidth")

        self.widget_population = QtWidgets.QWidget(self.centralwidget)
        self.widget_population.setGeometry(QtCore.QRect(0, 170, 821, 281))
        self.widget_population.setObjectName("widget_population")
        self.widget_population.hide()
        self.label_77 = QtWidgets.QLabel(self.widget_population)
        self.label_77.setGeometry(QtCore.QRect(20, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.widget_population)
        self.label_78.setGeometry(QtCore.QRect(440, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.widget_population)
        self.label_79.setGeometry(QtCore.QRect(440, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.widget_population)
        self.label_80.setGeometry(QtCore.QRect(10, 100, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.txt_n = QtWidgets.QLineEdit(self.widget_population)
        self.txt_n.setGeometry(QtCore.QRect(580, 40, 113, 20))
        self.txt_n.setObjectName("txt_n")
        self.txt_xbar_p = QtWidgets.QLineEdit(self.widget_population)
        self.txt_xbar_p.setGeometry(QtCore.QRect(160, 40, 113, 20))
        self.txt_xbar_p.setObjectName("txt_xbar_p")
        self.txt_sd = QtWidgets.QLineEdit(self.widget_population)
        self.txt_sd.setGeometry(QtCore.QRect(580, 110, 113, 20))
        self.txt_sd.setObjectName("txt_sd")
        self.txt_c_i = QtWidgets.QLineEdit(self.widget_population)
        self.txt_c_i.setGeometry(QtCore.QRect(350, 110, 71, 20))
        self.txt_c_i.setObjectName("txt_c_i")
        self.label_81 = QtWidgets.QLabel(self.widget_population)
        self.label_81.setGeometry(QtCore.QRect(20, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.widget_population)
        self.label_82.setGeometry(QtCore.QRect(500, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.widget_population)
        self.label_83.setGeometry(QtCore.QRect(250, 160, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.txt_1alpha = QtWidgets.QLineEdit(self.widget_population)
        self.txt_1alpha.setGeometry(QtCore.QRect(130, 170, 113, 20))
        self.txt_1alpha.setObjectName("txt_1alpha")
        self.txt_alpha = QtWidgets.QLineEdit(self.widget_population)
        self.txt_alpha.setGeometry(QtCore.QRect(330, 170, 113, 20))
        self.txt_alpha.setObjectName("txt_alpha")
        self.txt_zalpha = QtWidgets.QLineEdit(self.widget_population)
        self.txt_zalpha.setGeometry(QtCore.QRect(610, 170, 101, 20))
        self.txt_zalpha.setObjectName("txt_zalpha")
        self.label_84 = QtWidgets.QLabel(self.widget_population)
        self.label_84.setGeometry(QtCore.QRect(340, 210, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.widget_population)
        self.label_85.setGeometry(QtCore.QRect(300, 210, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.widget_population)
        self.label_86.setGeometry(QtCore.QRect(380, 210, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.lbl_left = QtWidgets.QLabel(self.widget_population)
        self.lbl_left.setGeometry(QtCore.QRect(150, 220, 121, 31))
        self.lbl_left.setText("")
        self.lbl_left.setObjectName("lbl_left")
        self.lbl_right = QtWidgets.QLabel(self.widget_population)
        self.lbl_right.setGeometry(QtCore.QRect(420, 220, 121, 31))
        self.lbl_right.setText("")
        self.lbl_right.setObjectName("lbl_right")
        self.btn_okpop = QtWidgets.QPushButton(self.widget_population)
        self.btn_okpop.setGeometry(QtCore.QRect(320, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_okpop.setFont(font)
        self.btn_okpop.setObjectName("btn_okpop")
        self.btn_okmode.clicked.connect(self.click_mod)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Statistics Program"))
        self.combo_selectProblem.setItemText(1, _translate("MainWindow", "pie Chart & par Chart"))
        self.combo_selectProblem.setItemText(2, _translate("MainWindow", "Histogram"))
        self.combo_selectProblem.setItemText(3, _translate("MainWindow", "Measures of Central Tendency"))
        self.combo_selectProblem.setItemText(4, _translate("MainWindow", "Interquartile Range & Box Plot"))
        self.combo_selectProblem.setItemText(5, _translate("MainWindow", "Correlation"))
        self.combo_selectProblem.setItemText(6, _translate("MainWindow", "Population"))
        self.label_2.setText(_translate("MainWindow", "Select Problem:"))
        self.btn_okpiepar.setText(_translate("MainWindow", "ok"))
        self.label_4.setText(_translate("MainWindow", "Enter your Data"))
        self.comb_pie_par.setItemText(1, _translate("MainWindow", "pie Chart"))
        self.comb_pie_par.setItemText(2, _translate("MainWindow", "par Chart"))
        self.label_5.setText(_translate("MainWindow", "Enter amount of Data"))
        self.label_6.setText(_translate("MainWindow", "Chosse Your Graph"))
        self.label_16.setText(_translate("MainWindow", "Enter amount of Data"))
        self.btn_okiqr.setText(_translate("MainWindow", "ok"))
        self.label_17.setText(_translate("MainWindow", "Mode:"))
        self.label_22.setText(_translate("MainWindow", "Mean:"))
        self.label_23.setText(_translate("MainWindow", "Midean:"))
        self.label_24.setText(_translate("MainWindow", "IQR:"))
        self.label_26.setText(_translate("MainWindow", "kind of IQR:"))
        self.label_32.setText(_translate("MainWindow", "Q2:"))
        self.label_33.setText(_translate("MainWindow", "Q1:"))
        self.label_34.setText(_translate("MainWindow", "Q3:"))
        self.label_38.setText(_translate("MainWindow", "Outliers:"))
        self.label_39.setText(_translate("MainWindow", "Etreme values:"))
        self.label_14.setText(_translate("MainWindow", "Enter amount of Data"))
        self.btn_okmode.setText(_translate("MainWindow", "ok"))
        self.label_13.setText(_translate("MainWindow", "Mode:"))
        self.label_20.setText(_translate("MainWindow", "Mean:"))
        self.label_21.setText(_translate("MainWindow", "Midean:"))
        item = self.tableWidget_r.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget_r.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_r.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zx"))
        item = self.tableWidget_r.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Zy"))
        item = self.tableWidget_r.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Zx * Zy"))
        self.label_25.setText(_translate("MainWindow", "R:"))
        self.label_18.setText(_translate("MainWindow", "Enter amount of Data X"))
        self.btn_okr.setText(_translate("MainWindow", "ok"))
        self.label_19.setText(_translate("MainWindow", "Enter amount of Data Y"))
        self.label_27.setText(_translate("MainWindow", "Kind of R:"))
        self.label_28.setText(_translate("MainWindow", "X\':"))
        self.label_29.setText(_translate("MainWindow", "Sx:"))
        self.label_30.setText(_translate("MainWindow", "Y\':"))
        self.label_31.setText(_translate("MainWindow", "Sy:"))
        self.label_35.setText(_translate("MainWindow", "b1:"))
        self.label_36.setText(_translate("MainWindow", "b0:"))
        self.label_37.setText(_translate("MainWindow", "E\':"))
        self.btn_oke.setText(_translate("MainWindow", "ok"))
        self.label_40.setText(_translate("MainWindow", "Enter X:"))
        self.label_15.setText(_translate("MainWindow", "Enter amount of Data"))
        self.btn_okhistogram.setText(_translate("MainWindow", "ok"))
        self.label_41.setText(_translate("MainWindow", "Range:"))
        self.label_42.setText(_translate("MainWindow", "Max Value:"))
        self.label_43.setText(_translate("MainWindow", "Class Width:"))
        self.label_44.setText(_translate("MainWindow", "No.of classes:"))
        self.label_45.setText(_translate("MainWindow", "Min Value:"))
        self.btn_okpop.setText(_translate("MainWindow", "ok"))
        self.label_77.setText(_translate("MainWindow", "Enter Avrage:"))
        self.label_78.setText(_translate("MainWindow", "sample size:"))
        self.label_79.setText(_translate("MainWindow", "standard devition:"))
        self.label_80.setText(_translate("MainWindow", "(%)confidance interval of the population on mean:"))
        self.label_81.setText(_translate("MainWindow", "1 - alpha:"))
        self.label_82.setText(_translate("MainWindow", "Z(alpha/2):"))
        self.label_83.setText(_translate("MainWindow", "alpha/2:"))
        self.label_84.setText(_translate("MainWindow", "M"))
        self.label_85.setText(_translate("MainWindow", "<"))
        self.label_86.setText(_translate("MainWindow", "<"))

        self.combo_selectProblem.currentTextChanged.connect(self.checkcombo)
        self.btn_okpiepar.clicked.connect(self.klick)
        self.btn_okhistogram.clicked.connect(self.klick_his)
        self.btn_okiqr.clicked.connect(self.klick_iqr)
        self.btn_okr.clicked.connect(self.correration)
        self.btn_oke.clicked.connect(self.kick_e)
        self.btn_okpop.clicked.connect(self.Click_pop)
    def checkcombo(self):
        if self.combo_selectProblem.currentText() == "pie Chart & par Chart":
            self.widget_pie_par.show()
            self.widget_hiostgram.hide()
            self.widget_mode.hide()
            self.widget_iqr.hide()
            self.widget_R.hide()
            self.widget_population.hide()
        elif self.combo_selectProblem.currentText() == "Histogram":
            self.widget_hiostgram.show()
            self.widget_pie_par.hide()
            self.widget_mode.hide()
            self.widget_iqr.hide()
            self.widget_R.hide()
            self.widget_population.hide()
        elif self.combo_selectProblem.currentText() == "Measures of Central Tendency":
            self.widget_mode.show()
            self.widget_pie_par.hide()
            self.widget_hiostgram.hide()
            self.widget_iqr.hide()
            self.widget_R.hide()
            self.widget_population.hide()
        elif self.combo_selectProblem.currentText() == "Interquartile Range & Box Plot":
            self.widget_iqr.show()
            self.widget_pie_par.hide()
            self.widget_hiostgram.hide()
            self.widget_mode.hide()
            self.widget_R.hide()
            self.widget_population.hide()
        elif self.combo_selectProblem.currentText() == "Correlation":
            self.widget_R.show()
            self.widget_pie_par.hide()
            self.widget_hiostgram.hide()
            self.widget_mode.hide()
            self.widget_iqr.hide()
            self.widget_population.hide()

        elif self.combo_selectProblem.currentText() == "Population":
            self.widget_population.show()
            self.widget_R.hide()
            self.widget_pie_par.hide()
            self.widget_hiostgram.hide()
            self.widget_mode.hide()
            self.widget_iqr.hide()

    def klick(self):
        choice = self.comb_pie_par.currentText()
        txt1 = self.txt_nameofdata.text()
        txt2 = self.txt_amountofdatapie.text()
        word = txt1.split(",")
        amount = txt2.split(",")
        int_amout = []
        for i in range(0, len(amount)):
            int_amout.append(int(amount[i]))
        if (choice == "par Chart"):
            y_pos = np.arange(len(word))
            plt.bar(y_pos, int_amout, align='center', alpha=0.5)
            plt.xticks(y_pos, word)
            plt.ylabel('Usage')
            plt.title('Programming language usage')
            plt.show()
        if (choice == "pie Chart"):
            explode = []
            for i in range(0, len(int_amout)):
                explode.append(0)
            colors = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue', 'red', 'blue', 'yellow']
            plt.pie(int_amout, explode=explode, labels=word, colors=colors,
                    autopct='%1.1f%%', shadow=True, startangle=140)
            plt.axis('equal')
            plt.show()

    def click_mod(self):
        amount = (self.txt_nameofdatamode.text()).split(",")
        int_amount = []
        for i in range(0, len(amount)):
            int_amount.append(float(amount[i]))
        int_amount.sort()
        c = 1
        ma = 0
        ok = False
        for i in range(0, len(int_amount) - 1):
            if (int_amount[i] == int_amount[i + 1]):
                c = c + 1
            if int_amount[i] != int_amount[i + 1] or i == len(int_amount) - 2:
                if (c > ma):
                    ma = c
                c = 1
        max_number = set()
        for x in int_amount:
            if int_amount.count(x) == ma:
                max_number.add(x)
        mean1 = statistics.mean(int_amount)
        self.lbl_mean.setText(str(mean1))
        median1 = statistics.median(int_amount)
        self.lbl_midean.setText(str(median1))
        if (len(max_number) > 2):
            self.lbl_mode.setText("No Mode")
        if (len(max_number) == 2):
            x = max_number.pop()
            y = max_number.pop()
            self.lbl_mode.setText(str(x) + "," + str(y))
        if (len(max_number) == 1):
            x = max_number.pop()
            self.lbl_mode.setText(str(x))

    def klick_his(self):
        choice = self.combo_selectProblem.currentText()
        amount = (self.txt_nameofdatahistogram.text()).split(",")

        int_amotnt = []
        for i in range(0, len(amount)):
            int_amotnt.append(int(amount[i]))
            num_bins = 5
            n, bins, patches = plt.hist(int_amotnt, num_bins, facecolor='blue', alpha=0.5)
        int_amotnt.sort()
        self.lbl_maxvalue.setText(str(int_amotnt[len(int_amotnt)-1]))
        self.lbl_minvalue.setText(str(int_amotnt[0]))
        self.lbl_range.setText(str(int_amotnt[len(int_amotnt)-1]-int_amotnt[0]))
        self.lbl_nclasses.setText(str(math.ceil(1+math.log(len(int_amotnt),2))))
        self.lbl_classwidth.setText(str(math.ceil((int_amotnt[len(int_amotnt)-1]-int_amotnt[0])/(math.ceil(1+math.log(len(int_amotnt),10))))))
        plt.show()

    def klick_iqr(self):
        amount = (self.txt_nameofdataiqr.text()).split(",")
        int_amount = []
        for i in range(0, len(amount)):
            int_amount.append(float(amount[i]))
        int_amount.sort()
        c = 1
        ma = 0
        ok = False
        for i in range(0, len(int_amount) - 1):
            if (int_amount[i] == int_amount[i + 1]):
                c = c + 1
            if int_amount[i] != int_amount[i + 1] or i == len(int_amount) - 2:
                if (c > ma):
                    ma = c
                c = 1
        max_number = set()
        for x in int_amount:
            if int_amount.count(x) == ma:
                max_number.add(x)
        mean1 = statistics.mean(int_amount)
        self.lbl_mean_2.setText(str(mean1))
        median1 = statistics.median(int_amount)
        self.lbl_midean_2.setText(str(median1))
        if (len(max_number) > 2):
            self.lbl_mode_2.setText("No Mode")
        if (len(max_number) == 2):
            x = max_number.pop()
            y = max_number.pop()
            self.lbl_mode_2.setText(str(x) + "," + str(y))
        if (len(max_number) == 1):
            x = max_number.pop()
            self.lbl_mode_2.setText(str(x))
        iqr = iqr_fun(int_amount, len(int_amount),self,median1)
        self.lbl_iqr.setText(str(iqr))
        plt.boxplot(int_amount)
        plt.show()

    def correration(self):
        txt_x=(self.txt_nameofdatax.text()).split(",")
        txt_y=(self.txt_nameofdatay.text()).split(",")
        xLi=[]
        yLi=[]
        for i in range (0,len(txt_x)):
            xLi.append(int(txt_x[i]))
            yLi.append(int(txt_y[i]))
        ZxLi = getZ_Score(xLi)
        ZyLi = getZ_Score(yLi)
        sumZ = []
        self.tableWidget_r.setRowCount(len(xLi))
        for i in range(0, len(ZxLi)):
            x=ZxLi[i] * ZyLi[i]
            sumZ.append(x)
            #print("x",x)
        for i in range(0,len(xLi)):
            self.tableWidget_r.setItem(i,0, QTableWidgetItem(str(xLi[i])))
            self.tableWidget_r.setItem(i,1, QTableWidgetItem(str(yLi[i])))
            self.tableWidget_r.setItem(i,2, QTableWidgetItem(str(ZxLi[i])))
            self.tableWidget_r.setItem(i,3, QTableWidgetItem(str(ZyLi[i])))
            self.tableWidget_r.setItem(i,4, QTableWidgetItem(str(sumZ[i])))
        r=(math.fsum(sumZ)) / (len(sumZ) - 1)
        self.lb_xbar.setText(str(statistics.mean(xLi)))
        self.lb_ybar.setText(str(statistics.mean(yLi)))
        self.lb_sx.setText(str(statistics.stdev(xLi)))
        self.lb_sy.setText(str(statistics.stdev(yLi)))
        self.lb_r.setText(str(r))

        KIND=""
        SIGNAL=""
        if r==1 or r==-1:
            KIND="Perfect"
        if (r<1 and r>0.6) or (r>-1 and r<-0.6):
            KIND="Strong"
        if (r<0.7 and r>0.3) or (r>-0.7 and r<(-0.3)):
            KIND="Moderate"
        if (r>0 and r<0.4) or(r<0 and r>-0.4):
            KIND="Weak"
        if(r<0):
            SIGNAL="Inverse"
        if(r>0):
            SIGNAL="Direct"
        self.lb_kindofr.setText(SIGNAL+" "+KIND)

    def kick_e(self):
        if(self.txt_e.text()!=""):
            s=float(self.lb_sy.text())
            SS=float(self.lb_sx.text())
            r=float(self.lb_r.text())
            b1 = (s /SS)*r
            m= float(self.lb_xbar.text())
            MM=float(self.lb_ybar.text())
            b0 = MM - (b1 * m)
            e = float(self.txt_e.text())
            E = b0 + (b1*e)
            self.lb_e.setText(str(E))
            self.lb_b1.setText(str(b1))
            self.lb_b0.setText(str(b0))
            self.lb_e.setText(str(e))

    def Click_pop(self):
        Pop_mean=float(self.txt_c_i.text())
        standard_dev=float(self.txt_sd.text())
        enter_avg=float(self.txt_xbar_p.text())
        sample_size=int(self.txt_n.text())
        Pop_mean2=(Pop_mean/100)
        self.txt_1alpha.setText(str(Pop_mean2))

        alphaiv2=round(((1-Pop_mean2)/2),4)
        self.txt_alpha.setText(str(alphaiv2))
        z=get_z(alphaiv2)
        self.txt_zalpha.setText(str(z))
        var=math.sqrt(sample_size)
        error=z*(standard_dev/var)
        varright=str(enter_avg+error)
        varleft=str(enter_avg-error)
        self.lbl_left.setText(str(varright))
        self.lbl_right.setText(str(varleft))

if __name__ == "__main__":
    import sys
    import math
    import statistics

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

